openai: 3.0.0
info:
  title: Estim AI API
  version: 1.0.0
tags:
  - name: dashboard
    description: ''
  - name: estimate
    description: ''
  - name: explorate
    description: ''

path:
  /dashboard:
    get:
      tags:
        - dashboard
      summary: Get a list of properties
      responses:
        '200':
          description: List of properties
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dashboard'